/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package manageyourmusic;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author pylyp
 */
public class LikedPlaylistGUI extends javax.swing.JFrame {

    /**
     * Creates new form LikedPlaylistGUI
     */
    LikedPlaylist likedPlaylist;
    GenrePlaylist genrePlaylist1;
    GenrePlaylist genrePlaylist2;
    ArrayList<String> playlistStr;
    Composition comp;
    
    public LikedPlaylistGUI() {
        initComponents();
        //Center form in screen
        setLocationRelativeTo(null);
    }
    
    public void setPlaylists(LikedPlaylist likedPlaylist, GenrePlaylist genrePlaylist1, GenrePlaylist genrePlaylist2){
        this.likedPlaylist = likedPlaylist;
        this.genrePlaylist1 = genrePlaylist1;
        this.genrePlaylist2 = genrePlaylist2;
        lblSongsCount.setText(String.valueOf(likedPlaylist.getCompCount()));
        displayPlaylist();
    }
    
    private void displayPlaylist() {
        textArea.setText("");
        for (int i = 0; i < likedPlaylist.getCompCount(); i++) {
            textArea.append(likedPlaylist.compositions.get(i).toString() + "\n");
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        lblSongsCount = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        btnMove = new javax.swing.JButton();
        btnDel = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        btnPrint = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tfTitle = new javax.swing.JTextField();
        tfArtist = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Liked Playlist");

        textArea.setColumns(20);
        textArea.setRows(5);
        jScrollPane1.setViewportView(textArea);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("Songs");

        lblSongsCount.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblSongsCount.setText("##");

        btnAdd.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnMove.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnMove.setText("Move");
        btnMove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoveActionPerformed(evt);
            }
        });

        btnDel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnDel.setText("Del");
        btnDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelActionPerformed(evt);
            }
        });

        btnSearch.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnPrint.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnPrint.setText("Print");
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setText("Title:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setText("Artist:");

        tfTitle.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        tfArtist.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel5.setText("•");

        btnBack.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(242, 242, 242))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnAdd)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnMove)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnDel)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(tfTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tfArtist, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSearch)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPrint)
                        .addGap(0, 50, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblSongsCount)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBack)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel5)
                        .addComponent(jLabel2)
                        .addComponent(lblSongsCount))
                    .addComponent(btnBack))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfArtist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnMove)
                    .addComponent(btnDel)
                    .addComponent(btnSearch)
                    .addComponent(btnPrint))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        if(tfTitle.getText().isEmpty() || tfArtist.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "You missed some input lines");
        }else{
            String title = tfTitle.getText();
            String artist = tfArtist.getText();
                        
            comp = new Composition(title, artist);
            likedPlaylist.pushComp(comp);
            
            //change songs count
            lblSongsCount.setText(String.valueOf(likedPlaylist.getCompCount()));
            
            //clean input
            tfTitle.setText("");
            tfArtist.setText("");
            
            //display playlist
            displayPlaylist();
            
        }
    }//GEN-LAST:event_btnAddActionPerformed

    public LikedPlaylist getLikedPlaylist() {
        return likedPlaylist;
    }

    public GenrePlaylist getGenrePlaylist1() {
        return genrePlaylist1;
    }

    public GenrePlaylist getGenrePlaylist2() {
        return genrePlaylist2;
    }
    
    
    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        HomeGUI homeGUI = new HomeGUI();
        homeGUI.setPlaylists(getLikedPlaylist(), getGenrePlaylist1(), getGenrePlaylist2());
        homeGUI.setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnMoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoveActionPerformed
        // TODO add your handling code here:
        //Move the last added song from liked playlist to genre playlist
        String userInput = JOptionPane.showInputDialog(null, "Please enter the number of playlist to move 1)Genre1 2)Genre2");
        Composition lastAddedSong = likedPlaylist.popComp();
        System.out.println(lastAddedSong);
        if ("1".equals(userInput) && lastAddedSong != null) {
            genrePlaylist1.addComp(lastAddedSong);
            System.out.println("Moved song '" + lastAddedSong.title + "' to 'Genre 1' playlist.");
        } else if ("2".equals(userInput) && lastAddedSong != null) {
            genrePlaylist2.addComp(lastAddedSong);
            System.out.println("Moved song '" + lastAddedSong.title + "' to 'Genre 2' playlist.");
        } else {
            JOptionPane.showMessageDialog(null, "Error.");
        }

        //change songs count
        lblSongsCount.setText(String.valueOf(likedPlaylist.getCompCount()));

        //display playlist
        displayPlaylist();

    }//GEN-LAST:event_btnMoveActionPerformed

    private void btnDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelActionPerformed
        // TODO add your handling code here:
        if(tfTitle.getText().isEmpty() && tfArtist.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Enter at least one criteria");
        }else{
            String keyword;
            
            if (!tfTitle.getText().isEmpty()){
                keyword = tfTitle.getText();
            }else{
                keyword = tfArtist.getText();
            }
            
            if(likedPlaylist.search(keyword).isEmpty()){
                JOptionPane.showMessageDialog(null, "Nothing found");
            }else{
                //deleting composition by keyword title either artist
                likedPlaylist.deleteComp(likedPlaylist.search(keyword).get(0));
                
                //change songs count
                lblSongsCount.setText(String.valueOf(likedPlaylist.getCompCount()));

                //clean input
                tfTitle.setText("");
                tfArtist.setText("");

                //display playlist
                displayPlaylist();
                
            }
        }
    }//GEN-LAST:event_btnDelActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        if(tfTitle.getText().isEmpty() && tfArtist.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Enter at least one criteria");
        }else{
            String keyword;
            // choosing keyword
            if (!tfTitle.getText().isEmpty()){
                keyword = tfTitle.getText();
            }else{
                keyword = tfArtist.getText();
            }
            
            ArrayList<Composition> searchRes = new ArrayList<>();
            searchRes = likedPlaylist.search(keyword);
            
            if(searchRes.isEmpty()){
                JOptionPane.showMessageDialog(null, "Nothing found");
            }else{
                textArea.setText("Search results: ");
                for (int i = 0; i < searchRes.size(); i++){
                    textArea.append("\n" + searchRes.get(i).toString());
                }

                //clean input
                tfTitle.setText("");
                tfArtist.setText("");
                
            }
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        // TODO add your handling code here:
        displayPlaylist();
    }//GEN-LAST:event_btnPrintActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LikedPlaylistGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LikedPlaylistGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LikedPlaylistGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LikedPlaylistGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LikedPlaylistGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDel;
    private javax.swing.JButton btnMove;
    private javax.swing.JButton btnPrint;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblSongsCount;
    private javax.swing.JTextArea textArea;
    private javax.swing.JTextField tfArtist;
    private javax.swing.JTextField tfTitle;
    // End of variables declaration//GEN-END:variables
}
